source "https://rubygems.org"

# Configuración para Ruby 3.0.1+ (via rbenv)
ruby ">= 3.0.0"

gem "jekyll", "~> 4.3.0"
gem "jekyll-seo-tag", "~> 2.8"
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-sitemap", "~> 1.4"
end

# Markdown
gem "kramdown", "~> 2.4"
gem "kramdown-parser-gfm", "~> 1.1"
